#Application http://localhost:8081/api/v1/person/swagger-ui.html#/persons
application:
  name: person-apipositive-validation-bff
#General configuration
server:
  port: 8081
  servlet:
    context-path: /api/v1/person
# Data source configuration
spring:
  application:
    name: person-api
  h2:
    console:
      enabled: true
      #http://localhost:8081/api/v1/person/h2-console/
# Spring Actuator Configuration
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
springfox:
  documentation:
    swagger:
      v2:
        path: /bff-docs
#Swagger API doc
swagger:
  allowed: true
  api:
    title: Person API
    version: '@project.version@'
    description: Base service for an API
person:
  success: The operation was successful.
  prefix: 'API-PSN:'
  channel-id: ${mercury.channel.id}
  error:
    general: There was an unexpected error. Please try again.